Repository hoprnet/myne-chat, pull requests merged in 2021-12, with the labels that each got.

#29 reconnect WS
  src/components/personal-panel.tsx
  src/state/index.ts
  src/state/user.ts
  src/state/websocket.ts
Labels: bug

#31 simplify state
  src/components/analytics.tsx
  src/state/index.ts
  src/state/user.ts
  src/state/websocket.ts
Labels: enhancement

#34 fix mocks
  mocks/index.js
  package.json
  pages/index.tsx
  src/state/index.ts
  src/state/user.ts
  src/state/websocket.ts
  src/theme.ts
  src/utils.ts
  yarn.lock
Labels: bug

#35 Enable using the security token for websocket connections
  mocks/index.js
  package.json
  src/state/websocket.ts
  yarn.lock
Labels: enhancement

#40 Add simple tutorial to run Myne Chat and hoprd
  README.md
  mocks/index.js
  package.json
  src/state/index.ts
Labels: documentation

#51 Supported `422` error response
  pages/index.tsx
Labels: bug
